# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-14 21:12
from __future__ import unicode_literals

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Cliente'), (2, 'Comum'), (3, 'Admin')], default=2, verbose_name='Tipo')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=account.models.path_avatar, verbose_name='Avatar')),
                ('birdayth', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
