# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-28 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Cliente'), (1, 'Cliente Villa'), (2, 'Comum'), (3, 'Admin')], default=2, verbose_name='Tipo'),
        ),
    ]
