# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-02 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170901_2110'),
        ('account', '0002_auto_20180528_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Cliente'), (1, 'Comum'), (2, 'Admin')], default=1, verbose_name='Tipo'),
        ),
    ]
