# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-07 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('account', '0004_remove_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.GrupoCliente'),
        ),
    ]
