language: python
python:
    - "3.5.1"
install:
    - pip install -q -r requirements.txt
    - python contrib/generate_.env.py
    - python django-pure-pagiation/setup.py install
script:
- python manage.py test --nomigrations