version: '3'

services:
  web:
    build: .
    restart: always
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=please_change_me
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  db:
    restart: always
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/servigraf/data/
volumes:
  postgres_data:
