# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-22 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'produto'), (2, 'serviço')], default=1, verbose_name='Tipo'),
        ),
    ]
