# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-23 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20170823_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50, unique=True, verbose_name='Grupo')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='GrupoProduto',
        ),
        migrations.AddField(
            model_name='produto',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='catalogo.GroupProduct'),
        ),
    ]
