# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-01 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20170823_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupproduct',
            options={'ordering': ['group'], 'verbose_name': 'Grupo de Produto', 'verbose_name_plural': 'Grupos de Produtos'},
        ),
    ]
