# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20170901_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
