# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-18 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('observacao', models.TextField(blank=True, verbose_name='Descrição')),
                ('documento', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('ativo', models.NullBooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Juridico'), (2, 'Fisico')], default=1, verbose_name='Fisico/Juridico')),
                ('ramo', models.CharField(blank=True, max_length=20, verbose_name='Ramo')),
                ('mensalista', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cli_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobre_nome', models.CharField(max_length=30)),
                ('observacao', models.TextField(verbose_name='observação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Contato',
                'abstract': False,
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail')),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.Contato')),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-mails',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=20, verbose_name='Lagradouro')),
                ('endereco', models.CharField(max_length=60, verbose_name='Endereçoo')),
                ('numero', models.PositiveIntegerField(verbose_name='Numero')),
                ('complemento', models.CharField(max_length=40, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=11, verbose_name='Cep')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=20, verbose_name='UF')),
                ('tipo_end', models.PositiveIntegerField(choices=[(1, 'Resindencial'), (2, 'Comercial'), (3, 'Entrega'), (4, 'Faturamento')], default=2, verbose_name='Tipo Endereço')),
                ('observacao', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('ddd', models.CharField(max_length=3, verbose_name='DDD')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('tipo', models.PositiveIntegerField(choices=[('TELEFONE FIXO', 1), ('TELEFONE FAX', 2), ('TELEFONE CASA', 3), ('TELEFONE TRBALHO', 4), ('TELEFONE CELULAR', 5), ('TELEFONE CELULAR TIM', 6), ('TELEFONE CELULAR CLARO', 7), ('TELEFONE CELULAR VIVO', 8), ('TELEFONE CELULAR VIVO', 9)], default=1, verbose_name='Tipo')),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='core.Contato')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
    ]
