# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-25 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170721_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='observação'),
        ),
    ]
