# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-03 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contato_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
