# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-08 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_endereco_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(max_length=60, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=20, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
