# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-09 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170808_2130'),
        ('core', '0007_auto_20170808_1553'),
    ]

    operations = [
    ]
