# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-22 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['-id'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['-id'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
    ]
