# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170822_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Juridico'), (2, 'Fisico')], default=1, verbose_name='Fisico/Juridico'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
