# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-01 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170901_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ramo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ramo'),
        ),
    ]
