# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-11 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Projeto')),
                ('desc', models.TextField(verbose_name='Desccrição')),
            ],
            options={
                'verbose_name_plural': 'Projetos',
                'verbose_name': 'Projeto',
            },
        ),
    ]
