# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170901_2110'),
        ('project', '0002_auto_20171005_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField(default=True, verbose_name='Ativo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_client', to='core.Cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='clients',
            field=models.ManyToManyField(through='project.ProjectClient', to='core.Cliente'),
        ),
        migrations.AddField(
            model_name='projectclient',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_client', to='project.Projects'),
        ),
    ]
