# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-23 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170901_2110'),
        ('project', '0003_auto_20171123_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='clients',
            field=models.ManyToManyField(through='project.ProjectClient', to='core.Cliente'),
        ),
    ]
