# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-22 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20171122_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
        migrations.AlterField(
            model_name='projectclient',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Projects'),
        ),
    ]
