# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-23 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projects_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclient',
            name='active',
            field=models.NullBooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
